/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1" // shadow plugin 추가
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.junit.junit)
    // https://mvnrepository.com/artifact/org.assertj/assertj-core
    testImplementation("org.assertj:assertj-core:3.27.3")
}

group = "org.nhnnext"
version = "1.0"
description = "web-application-server"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

// fat JAR (all dependencies 포함) 생성 및 Main-Class 명시
tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    archiveClassifier.set("") // 기본 jar 이름 사용 (ex: web-application-server-1.0.jar)
    manifest {
        attributes["Main-Class"] = "webserver.WebServer"
    }
}

// build 시 shadowJar도 같이 실행되도록 설정
tasks.build {
    dependsOn(tasks.shadowJar)
}